### ISSUE TITLE
NetworkReader doesn't properly handle EOL

### ISSUE THREAD

**Issue by julianrace** [davidpablocohn/openrvdas#108]
NetworkReader simply reads the UDP datastream.   Data sentences may come in via separate packets, so when you call socket.recv you might be getting all or part of a sentence, or multiple sentences. 
The read routine must gracefully handle UDP incoming data and split it into individual messages.

For example, when reading UDP data from a GPS, this entire text gets treated as a single 'record'
2019-05-09T17:53:10.345749Z $GPZDA,175308.00,09,05,2019,00,00*68
$GPGGA,175308.00,2745.713986,N,08237.912760,W,2,09,1.4,21.357,M,-26.124,M,2.0,0403*4D
$GPVTG,0.0,T,,M,0.01,N,0.02,K,D*0B
$GPGLL,2745.713986,N,08237.912760,W,175308.00,A,D*75
$GPRMC,175308.00,A,2745.713986,N,08237.912760,W,0.01,0.0,090519,0.0,E,D*1C

**Comment by davidpablocohn** [comment]
Ahyup - this could definitely cause problems. It does raise a conundrum,
though, that Toby Martin would wag his finger at:

Those records were all emitted by the device at the same instant. But if
they are processed as separate, sequential records, they will have slightly
different, sequential timestamps. How much does that matter? Should the
NetworkReader insist that records are EOL-terminated? Or, like with #106
and SerialReaders, should we allow specifying what character (if any)
terminates a record? (If no termination character is given, the record
would be just whatever comes in a network packet).
