### ISSUE TITLE
Mysql working very too hard.

### ISSUE THREAD

**Issue by LMG-ET** [davidpablocohn/openrvdas#147]
**Describe the bug**

On the LMG, Django is making over 300 queries to mysql per second, resulting in unnecessarily large CPU load and IO burden. 

**To Reproduce**
Start logging on the LMG (running lmg_test branch of repo on Red Hat Enterprise Linux Server release 7.6 (Maipo).
Verify mysql activity using:
mysqladmin -u <openrvdas user> -p<openrvdas mysql password> status

**Expected behavior**
To provide status information to the listeners and Django GUI, only a small (configurable?) number per second queries should be required (request status of all loggers at once, parse and distribute information).

**Screenshots**
**mysqladmin:**
![image](https://user-images.githubusercontent.com/8374302/62469889-bca6e400-b788-11e9-9d2e-ebbb99b228aa.png)
**top**:
![image](https://user-images.githubusercontent.com/8374302/62469946-d47e6800-b788-11e9-9fea-0a92588fca04.png)
**iotop**:
![image](https://user-images.githubusercontent.com/8374302/62470138-4787de80-b789-11e9-8fd4-68b0ade71691.png)

**Additional context**
Using lmg_test branch of GitHub repo.

**Comment by davidpablocohn** [comment]
Note to self: this is because the api.update_status() (which is called once per second) method is hopelessly naive, and calls a plethora of other api methods, each with their own MySQL calls, to build its status report.

**Comment by davidpablocohn** [comment]
Cached django_server_api appears to have brought this to heel.
