### ISSUE TITLE
Show running config

### ISSUE THREAD

**Issue by julianrace** [davidpablocohn/openrvdas#153]
Add a page to the dashboard showing the full current running config

**Comment by davidpablocohn** [comment]
Do you mean being able to see the full definition for a logger's current
configuration? I've been thinking we should have something like that when
you select a logger. The pop up that lets you select/change a logger's
config should also show you the full definition for that config and maybe
even give you a check box where you can monitor that logger's output. (Of
course the latter is complicated by the fact that, what the logger outputs,
and to where it outputs it depends on the configuration...)

**Comment by julianrace** [comment]
Yes, I want to be able to at a glance see what the current configuration is for each logger, including outputs.
I.E.  I want to see what UDP outputs the GPS is currently set up to deliver.

**Comment by davidpablocohn** [comment]
Now fixed in dev branch. Will be merged into master at next version
