### ISSUE TITLE
Should Transforms inherit from Readers and Writers?

### ISSUE THREAD

**Issue by davidpablocohn** [davidpablocohn/openrvdas#24]
Instead of being a standalone base class. Would allow both read() and write() methods in addition to the expected transform() method, but they do make some sense in async execution.

**Comment by webbpinner** [comment]
If transforms was a stand-alone class, could they be used to process/reprocess existing files?

For example: transforming a csv-formatted file to a JSON object.

This might open up some interesting possibilities for using the transform class to build custom dataset post-collection.

**Comment by davidpablocohn** [comment]
I think you can already do that, right?  Pull the data you want from
file/database using a Reader, pipe it through the Transform(s) you want,
then write it back to a different file/database. That's how I created the
sample data in test/

You can *almost* do the example you describe from listen.py, except that I
didn't implement a command line flag to trigger the ParseNMEATransform's
as_json() method. The method is already implemented and the NMEA parser can
output as either a Python object or JSON (I just realized that my
"Components"
<https://docs.google.com/document/d/1Ppl0kLVOEjs0pFPX2RKgWQIm1At3h5K71W1D9tgUJaM/edit#heading=h.z8bn3w58f7fc>
doc didn't document the existence of that flag - added now.)

**Comment by webbpinner** [comment]
Right... still wrapping my head around the architecture.

**Comment by davidpablocohn** [comment]
Understood! The architecture's been in my head for a while, but I still
keep finding my own head needing extra wraps.
