### ISSUE TITLE
Logger configuration management

### ISSUE THREAD

**Issue by davidpablocohn** [davidpablocohn/openrvdas#28]
Aggregate configurations into a dictionary where keys are config names (e.g. gyr1-writeall) and values are logger configurations (e.g. {"readers":...,}). A cruise mode would be a list of logger configs:   "underway": ["gyr1-writeall", ...] where logger configs could be either names or entire inline definitions.

**Comment by davidpablocohn** [comment]
Consensus seems to be that we want something in either YAML or JSON that provides structural validation. My inclination is now to just externalize any clever parsing that needs to be done. Have the system read in a full JSON/YAML dict explicitly declaring each configuration. Given that the representation is complete, and simply has to get interpreted as a Python dict, it should be pretty easy to swap in modules that will take either JSON or YAML.

But to save humans from having to create and debug the complete dict, we should have a build_configurations.py script that takes a compact human-readable representation with variables like "deployment_id" (more general than "cruise"), mnemonic mode names and templates, and generates the full JSON/YAML dict in question.

**Comment by webbpinner** [comment]
Would it be possible to include a "dry-run" option on that build_configuration.py script that produces a human-readable report of what the resulting logger will look like?  This would be analogous to the testparm program included with Samba.

Other random thoughts based on experiences with Apache's config management...
Within Apache there can be multiple site configs.  In some cases multiple sites can be run simultaneously, in other cases different versions of a site configure are swapped out.  Managing with site configs are used is handled via cli.  The way Apache does this is to store all site config files (which are XML) in a directory called "sites-available".  Two scripts, `a2ensite` and `a2dissite` enable/disable site configs by simply creating/destroying symlinks to the sites configs in a directory called "sites-enabled".  When Apache is started, restarted or reloaded it dynamically configures itself based on the site config files (symlinks) within the "sites-enabled" folder.  Just wanted to put that solution out there to help continue the discussion.

**Comment by davidpablocohn** [comment]
I do like the idea of having a directory of configs, with the option of one of them being the default (along with having a default mode, so if the system wakes up and has no other instructions, it loads the available configurations and puts its loggers into the default mode). The symlink idea might be a simple way to implement that.

I also like the idea of a --dry_run option (or maybe an --explain_this_to_me option?) that produces a report like you describe that emphasizes readability.

I was figuring that the expanded config would still be human readable, just voluminous. And that you'd write that out to file. E.g.

```
scripts/build-configuration.py --json my_compact_config.json > local/configurations/expanded_config.json

openrvdas/manager/run_loggers.py --config local/configurations.expanded_config.json
```
Where my_compact_config.json might be something like I'd proposed earlier:
```
{
    "vars": {
        "%CRUISE%" : "NBP1700",
        "%LOGFILE_BASE%": "/tmp/log/%CRUISE%",
        "%UDP_PORT%": ":6224"
    },
    "modes": {
        // Nothing's running when off
        "off": {},
        
        // In port, we only run certain instruments, and don't write to disk
        "port": {
            "vars": {"%INST%": ["gyr1", "mwx1", "s330", "eng1", "rtmp"]},
            "loggers":  {"%INST%": "SERIAL_LOGGER_NO_WRITE"}
        },
        ...
```
or whatever someone more clever/obsessed comes up with. And the expanded_config.json is just the full, unmitigated JSON without any of the clever substitutions in it:
```
  'knud_SERIAL_LOGGER': {
    'readers': {'class': 'SerialReader',
                'kwargs': {'baudrate': 9600,
                           'port': '/tmp/tty_knud'}},
    'transforms': {'class': 'TimestampTransform'},
    'writers': [{'class': 'LogfileWriter',
                 'kwargs': {
                   'filebase': '/tmp/logs/NBP1700/knud/raw/NBP1700_knud'}},
                {'class': 'ComposedWriter',
                 'kwargs': {
                   'transforms': {'class': 'PrefixTransform',
                                  'kwargs': {'prefix': 'knud'}},
                   'writers': {'class': 'NetworkWriter',
                               'kwargs': {'network': ':6224'}
                   }
                 }
                }
    ]
  }
}
```
