### ISSUE TITLE
How to store wildcards, configurations, cruise_modes etc in files/memory?

### ISSUE THREAD

**Issue by davidpablocohn** [davidpablocohn/openrvdas#29]
We can store each of the components as key/value pairs in a dictionary, but should those each be read from separate files and merged? Should they all be in one big dictionary? If so, should they each have their own key {"wildcards":..., "configurations": ..., ....} or all be top level?

Discussed briefly in the [configuration files document](https://docs.google.com/document/d/19IIv33rfHzI99fMoo-RvYbtGSOSgo_uwBqrp2THGDvY/edit#heading=h.b05fopm81i21)

**Comment by webbpinner** [comment]
There's a lot of documentation in those config files, enough that I could see them treated as a dataset themselves that are included somewhere in the final cruise data package.

Regarding wild cards and cruise modes I'd probably setup a pre-processor that would merge each of the config file templates with a lookup table containing the wildcard values for the current cruise.

The output would be a config file with the wildcards replaced with correct values.  That file would then be used to setup/restart a logger.

Using this model the techs would only need to modify the lookup table and re-run the pre-processor.

Thinking ahead to a future GUI... with this approach a GUI could create/update the lookup table file/object, and trigger a background process to build the final config files.  Another background process would then start/restart the loggers for which their configurations had changed.

Regarding a merged configuration file to handle multiple loggers...
One of the most common critiques I hear about SCS is that whenever a change is made to the configuration the entire acquisition system must be restarted.  Often operators simply want to tweak the label or sentence definition of a single logger and then start/restart that logger.  I can see the advantages (and challenges) with this approach vs a restart-all-the-things approach.   Before making any drastic changes, I would wait to hear if the rest of the community agrees.

**Comment by davidpablocohn** [comment]
Ahyup - that's *exactly* what I've been trying to get my head around,
messing with on my laptop. You could define a serial reader as, e.g.

    "knud_reader": { "class": "SerialReader",

                     "kwargs": {"port": "/tmp/tty_knud"

                               }
    }

Then have different functionality described for different cruise modes (in
port, underway, no_write) as knud_port, knud_underway, etc via

    "%INST%_underway": {

        "readers": "%INST%_reader",

        "transforms": [

            {"class": "TimestampTransform"},

            {"class": "PrefixTransform",

             "kwargs": {"prefix": "%INST%"}

            }

        ],

        "writers": [

            {"class": "LogfileWriter",

             "kwargs": {"logfile": "/tmp/logs/current/%INST%/raw/%INST%"}

            },

            {"class": "NetworkWriter",

             "kwargs": {"network": ":6224"}

            }

        ]

    },

**Comment by webbpinner** [comment]
On the vessels I've worked with the whole "At-Sea" vs "In-Port" is handled in one of three ways:
1. They turn off data logging while in port
2. They leave the data logging running and add the data to either the cruise that just finished or the cruise that's going to start next
3. They treat in-port periods as their own cruise.

In all three cases ALL the data streams connected to the DAS are treated the same (everything on OR everything off).

Again I'd wait to heard back from other folks but I see having at-sea and in-port configurations for individual loggers within a single cruise as an unnecessary design criteria that if implemented would become one more task a tech would need to perform each cruise... an interesting idea though.

**Comment by davidpablocohn** [comment]
On the old NBP system we've got four or so different modes:

   1. off - nothing running
   2. port - met/nav on and driving the displays, but not writing to disk
   3. no_write - everything running, driving displays, but still not
   writing to disk
   4. underway - everything running, writing

All is considered the same cruise once you run the "new_cruise" script.

On the new NBP system, the create_new_cruise script creates a default set
of configurations for each logger, and a default set of cruise modes (each
of which has one are populated automatically when a new cruise is
configured, and the LoggerManager keeps its own log of which logger is in
which configuration.

I definitely agree that it's worth hearing what setups other ships
have/like, but I want to make the same sort of functionality ready in
OpenRVDAS so folks can poke at it and say either "Hey, that's actually
pretty nifty" or "Uh...no, too messy."

**Comment by davidpablocohn** [comment]
Handled to my satisfaction in f2a2b51 and 09fab08
