### ISSUE TITLE
socat path dependency and smtp dependency

### ISSUE THREAD

**Issue by davidpablocohn** [davidpablocohn/openrvdas#30]
Need to remove (or document!) these dependencies for other distributions. (E.g. Pi, Ubuntu, etc. which have socat in different places).

**Comment by webbpinner** [comment]
Don't forget about folks wanting to use OpenRVDAS on windows.  While I prefer Linux environments there are those that don't or perhaps can't use Linux-based OSs

**Comment by davidpablocohn** [comment]
I think, for now, I'm going to declare Windows beyond the scope of supportable compatibility. I've wrapped socat in a /bin/env lookup, and wrapped smtp in an exception catcher, so I'm going to declare this closed for now.
