### ISSUE TITLE
JSON config files should use Javascript-style // comment prefixes

### ISSUE THREAD

**Issue by davidpablocohn** [davidpablocohn/openrvdas#35]
JSON itself doesn't support comments, but we're using JSON for config files, and config files really need comments.

The logger.utils.read_json scripts strip out comments beginning with "#", in Python style, but JSON is *Javascript* Object Notation, so comments should really be Javascript format.

**Comment by webbpinner** [comment]
I know this issue is marked as closed but just for thought... was YAML ever considered as a format for config files?

**Comment by davidpablocohn** [comment]
Hadn't considered YAML. Did discuss XML and discarded it. But read_json() is only called in five files, and it should be pretty easy to tweak things to allow a read_yaml() function to be swapped in (hurrah for functions being assignable!). Pretty much anything that can convert text -> Python dict should work.
