### ISSUE TITLE
Adding unit of measure to message configs

### ISSUE THREAD

**Issue by webbpinner** [davidpablocohn/openrvdas#39]
If possible it would be useful to incorporate the ability to optionally define units of measure (uom) with in the message configuration files.

Ideally this information would be available when composing custom output message to writers and usable when building custom real-time displays (i.e. the display would be able to show the data value and uom)

**Comment by davidpablocohn** [comment]
Still need to implement #157, but the functionality of this is now complete and documented in docs/cached_data_server.md
