### ISSUE TITLE
Sample logger monitor

### ISSUE THREAD

**Issue by davidpablocohn** [davidpablocohn/openrvdas#41]
Two things, actually: a sample logger monitor config (say, winch or tmp to demonstrate) and a complete config in the style of test/configs/sample_cruise.json that includes monitors for all loggers.

**Comment by webbpinner** [comment]
I would suggest one of the examples (or perhaps adding a third example) be for a NMEA-style data stream such as GGA, HDT, DBT, etc.  Winch and temp are typically custom (non-NMEA compliant) formats.
