### ISSUE TITLE
Initial Django-based GUI implementation

### ISSUE THREAD

**Issue by davidpablocohn** [davidpablocohn/openrvdas#42]
Related to #36 - roadmap of initial implementation.

0.1. Load cruise config from file, display modes, and select modes, save back to file. 

0.2. Display will show all defined loggers and each config that exists for a logger. Allow selecting individual configs, then saving aggregated configs as a new mode.

0.3. Actually run/monitor the loggers as specified by the current config.

0.35. Save a history of current config to logfile

0.4. Allow editing of config vars (cruise id, logfile location, etc)

**Comment by webbpinner** [comment]
I completely agree that staying with python for the UI makes sense.  Is there an advantage/need for a fully fledged MVC framework like Django vs going with a micro framework like Flask?

**Comment by davidpablocohn** [comment]
Good question. In USAP, we picked Django arbitrarily, and were psyched to find the OSU folks using it, too. Don't really *need* Django's ORM and more esoteric features, but maximizing compatibility w/OSU is a priority for me. Of course, nothing to say that folks can't try GUIs in different languages - my roadmap calls for keeping the openrvdas/manager interactions API-driven.

Maybe worth throwing a query out to the mailing list to get a show of hands?
