### ISSUE TITLE
Support multiple cruises/views simultaneously

### ISSUE THREAD

**Issue by davidpablocohn** [davidpablocohn/openrvdas#59]
Different users may want different loggers running. If launching a UAV, want to run a sub-cruise (pun intended) without disturbing data acquisition of main cruise. Or may want a winches-only view, etc.

Users should be able to log into different roles and select from among cruises that that they are able to see and control.

**Comment by webbpinner** [comment]
Please don't take this is wrong way but this seems a little out-of-scope/feature creep.

The majority of potential users I talk with regularly aren't looking for a role-based logger initialization.  Many just want a logger that:
 - listens for incoming data via serial/network
 - optionally adds a timestamp
 - optionally performs a transform
 - optionally rebroadcasts the data via serial/udp
 - logs that data to a file.

Left unchecked these types of feature add-ons has the potential to transform a lightweight yet robust logger into a monolithic behemoth that is in many ways replicating the current state of underway loggers such as SCS.

I really think adding things like cruise awareness are unnecessary as in reality that metadata should be managed by a larger tool that can manage data from other collection systems (i.e. CTD, Multibeam, video, etc).  Placing cruise-specific metadata in any of these DAQs means there needs to be a process to sync that metadata for all of them... which would be a nightmare given most of these DAQs are closed-source.

I strongly recommend keeping this project focused on the bullet items listed above or risk the project discouraging potential users by being overly complex but again please take this as constructive criticism based on my own experience/opinions and based on conversations I've had with ship techs from multiple vessels.
