### ISSUE TITLE
graceful shutdown of logger_server.  

### ISSUE THREAD

**Issue by webbpinner** [davidpablocohn/openrvdas#64]
This applies to the issue_62 branch.

Doing a ^C when running logging_manager currently throws an KeyboardInterrupt traceback.  If you follow this with the "quit" command the program stops responding.  ^C must be applied again to exit the program.

Doing a ^D throws an EOFError and the program immediately exits.

As ^C and ^D are commonly used as ways to exit a python script it's probably worth redirectly these commands to use the same path used for the graceful shutdown.

**Comment by davidpablocohn** [comment]
Yes, this has actually been the problem that's been most dogging me with finishing up #62 - cleanly propagating the "exit" signal to all the threads and subprocesses has been surprisingly difficult.

**Comment by davidpablocohn** [comment]
Forgot to tag this on the commit that fixed it in issue_62 - the trick was keeping the input() thread as the main thread and making the rest daemons.
