### ISSUE TITLE
Need standardized code versioning strategy

### ISSUE THREAD

**Issue by davidpablocohn** [davidpablocohn/openrvdas#76]

**Comment by decibelhertz** [comment]
Would also be nice if the versions we tagged commits in this repo.  EG...
<img width="335" alt="screen shot 2018-11-04 at 6 55 12 am" src="https://user-images.githubusercontent.com/3743131/47965666-9a681600-dffe-11e8-8464-196ec1483048.png">
https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by davidpablocohn** [comment]
Excellent - adopted, thanks! Will begin a roadmap doc for what is needed to bring us to v0.8.0.
