### ISSUE TITLE
Simple Event Logger

### ISSUE THREAD

**Issue by davidpablocohn** [davidpablocohn/openrvdas#79]
Some sort of display widget such that a button push can create a data record that can be timestamped, stored, propagated, etc.

**Comment by webbpinner** [comment]
Pablo…

Take a look at this: https://sealog-jason.oceandatarat.org <https://sealog-jason.oceandatarat.org/>


=-------------------------------------------------=
Webb Pinner
Mobile: 401.749.9322
Email: webbpinner@gmail.com
Website: http://www.oceandatarat.org

**Comment by davidpablocohn** [comment]
This looks great, thanks!

For my own reference, sealog code is here:
 - client: https://github.com/webbpinner/sealog-client
 - server: https://github.com/webbpinner/sealog-server
